# Exploratory Data Analysis (EDA Basics) Assignment

In [1]:
# Import Libraries

import pandas as pd
import numpy as np

In [2]:
# Load Dataset

df = pd.read_csv("/content/House Price India.csv")

In [3]:
# Basic Dataset Checks

# Check Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

## Explanation

This shows:

- Number of rows and columns
- Data types
- Missing values

In [4]:
# Statistical Summary

df.describe()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
count,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04,14620.000000,14620.000000,14620.000000,14620.000000,...,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,14620.000000,1.462000e+04
mean,6.762821e+09,42604.538646,3.379343,2.129583,2098.262996,1.509328e+04,1.502360,0.007661,0.233105,3.430506,...,1970.926402,90.924008,122033.062244,52.792848,-114.404007,1996.702257,12753.500068,2.012244,64.950958,5.389322e+05
std,6.237575e+03,67.347991,0.938719,0.769934,928.275721,3.791962e+04,0.540239,0.087193,0.766259,0.664151,...,29.493625,416.216661,19.082418,0.137522,0.141326,691.093366,26058.414467,0.817284,8.936008,3.675324e+05
min,6.762810e+09,42491.000000,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,1900.000000,0.000000,122003.000000,52.385900,-114.709000,460.000000,651.000000,1.000000,50.000000,7.800000e+04
25%,6.762815e+09,42546.000000,3.000000,1.750000,1440.000000,5.010750e+03,1.000000,0.000000,0.000000,3.000000,...,1951.000000,0.000000,122017.000000,52.707600,-114.519000,1490.000000,5097.750000,1.000000,57.000000,3.200000e+05
50%,6.762821e+09,42600.000000,3.000000,2.250000,1930.000000,7.620000e+03,1.500000,0.000000,0.000000,3.000000,...,1975.000000,0.000000,122032.000000,52.806400,-114.421000,1850.000000,7620.000000,2.000000,65.000000,4.500000e+05
75%,6.762826e+09,42662.000000,4.000000,2.500000,2570.000000,1.080000e+04,2.000000,0.000000,0.000000,4.000000,...,1997.000000,0.000000,122048.000000,52.908900,-114.315000,2380.000000,10125.000000,3.000000,73.000000,6.450000e+05
max,6.762832e+09,42734.000000,33.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,...,2015.000000,2015.000000,122072.000000,53.007600,-113.505000,6110.000000,560617.000000,3.000000,80.000000,7.700000e+06

## Explanation

This gives:

- Mean
- Median (50%)
- Minimum value
- Maximum value
- Standarrd deviation

In [5]:
# Handle Missing Values

# Check Missing Values

df.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

# Explanation

- Counts missing values in each column.

In [6]:
# Remove Missing Values

df = df.dropna()

# Explanation

- Removes rows containg missing values.

In [7]:
# Q1. What is the average, median, and standard deviation of house prices?

average_price = df['Price'].mean()
median_price = df['Price'].median()
std_price = df['Price'].std()

print("Average Price:", average_price)
print("Median Price:", median_price)
print("Standard Deviation:", std_price)

Average Price: 538932.2183310534
Median Price: 450000.0
Standard Deviation: 367532.3808039669

## Explanation

- mean() -> average price
- median() -> middle value
- std() -> spread of prices

## Interpretation

- The average price represents the overall market value of houses in the dataset.
- The median price shows the middle house price and helps understand the central tendency without the effect of extreme values.
- The standard deviation indicates how much house prices vary from the average price.
- A high standard deviation means house prices differ greatly, while a low value means prices are more consistent.

In [8]:
# Q2. Which number of bedrooms is most common?

common_bedrooms = df['number of bedrooms'].mode()[0]

print("Most Common Bedrooms:", common_bedrooms)

Most Common Bedrooms: 3

## Explanation

 - mode() gives the most frequent value.

 ## Interpretation

- The most common number of bedrooms represents the type of house most frequently available or preferred in the market.
- This helps identify common housing demand among buyers.
- If 3-bedroom houses are most common, it suggests medium-sized family homes are popular.

In [9]:
# Q3. Check if the price data is skewed.

skewness = df['Price'].skew()

print("Skewness:", skewness)

Skewness: 4.269297720707116

## Expalantion

- skew() checks data distribution.

## Interpretation

- If the skewness value is positive, house prices are right-skewed, meaning a few expensive houses increase the average price.
- If skewness is negative, lower-priced houses dominate the dataset.
- House price datasets are usually positively skewed because luxury homes have extremely high prices compared to normal houses.

In [10]:
# Q4. What is the average price for each number of bedrooms.

avg_price_bedroom = df.groupby('number of bedrooms')['Price'].mean()

print(avg_price_bedroom)

number of bedrooms
1     3.089638e+05
2     3.985476e+05
3     4.632776e+05
4     6.361988e+05
5     7.752550e+05
6     8.375815e+05
7     1.016544e+06
8     1.208455e+06
9     7.766663e+05
10    8.200000e+05
11    5.200000e+05
33    6.400000e+05
Name: Price, dtype: float64

## Explanation

- Groups houses by bedroom count.
- Finds average price for each group.

## Interpretation

- This analysis helps understand how house prices change with bedroom count.
- Generally, houses with more bedrooms have higher prices because they provide more space and facilities.
- It helps buyers and real estate businesses understand pricing patterns based on house size.

In [11]:
# Q5. What is the relationship between living area and and price? (Use : Area without Basement)

correlation = df['living area'].corr(df['Price'])

print("Correlation:", correlation)

Correlation: 0.7121694766782514

## Explanation

- corr() measures relationship strength.

## Interpretation

- A positive correlation means larger living areas tend to have higher prices.
- A strong positive relationship indicates area is an important factor affecting house price.
- Buyers usually pay more for houses with larger living spaces.

In [12]:
# Q6. Identify any anomalies where houses have high prices but low areas.

anomalies = df[(df['Price'] > df['Price'].quantile(0.90)) &
               (df['living area'] < df['living area'].quantile(0.25))]

print(anomalies[['Price', 'living area']])

        Price  living area
81     900000         1330
6688   885000         1313
8104   888000         1250
10922  900000         1190
12692  900000         1240
12955  907000         1340
13163  903000         1140

## Explanation

Finds houses with:
- Very high price
- Small area

## Interpretation

- These houses are unusual because they have small areas but very high prices.
- Possible reasons may include:
(i) Premium location
(ii) Luxury interiors
(iii) Waterfront view
(iv) Special amenities
- Detecting anomalies helps identify unique or overpriced properties.

In [13]:
# Q7. Compare average price based on number of floors and houses with or without waterfront.

# Average Price by Floors

floor_price = df.groupby('number of floors')['Price'].mean()

print(floor_price)

number of floors
1.0    4.369769e+05
1.5    5.549301e+05
2.0    6.487372e+05
2.5    1.106233e+06
3.0    5.663281e+05
3.5    1.205875e+06
Name: Price, dtype: float64

In [14]:
# Average Price by Waterfront

waterfront_price = df.groupby('waterfront present')['Price'].mean()

print(waterfront_price)

waterfront present
0    5.304174e+05
1    1.641902e+06
Name: Price, dtype: float64

## Explanation

- Comapres house prices using categories.

## Interpretaion for Floors

- Houses with more floors may have higher prices because they provide more usable space.
- Multi-floor houses are often considered more luxurious or suitable for large families.

## Interpretation for Waterfront

- Waterfront houses generally have higher prices because scenic locations increase property value.
- This shows location and surroundings strongly affect real estate prices.

In [15]:
# Q8. Identify the minimum and maximum house price. What does this indicate?

minimum_price = df['Price'].min()
maximum_price = df['Price'].max()

print("Minimum Price:", minimum_price)
print("Maximum Price:", maximum_price)

Minimum Price: 78000
Maximum Price: 7700000

## Explanation

- min() gives lowest price.
- max() gives highest price.

## Interpretation

- The minimum price represents the least expensive house in the dataset.
- The maximum price represents the most luxurious or premium property.
- The difference between minimum and maximum prices shows the price range and diversity of the housing market.

In [16]:
# Q9. Which location (zipcode/area) has the highest average price?

highest_location = df.groupby('Postal Code')['Price'].mean().sort_values(ascending=False)

print(highest_location.head(1))

Postal Code
122071    2.348311e+06
Name: Price, dtype: float64

## Explanation

- Groups prices by postal code.
- Finds highest average price location.

## Interpretation

- The location with the highest average price is likely a premium residential area.
- High prices may be due to:
(i) Better infrastructure
(ii) Good connectivity
(iii) Luxury facilities
(iv) High demand
- This analysis helps identify valuable real estate locations.

## Q10. Write at least 5 insights from your analysis.

Insights:

- House prices are positively skewed because a few luxury houses are extremely expensive.
- Houses with more bedrooms generally have higher prices.
- Living area has a strong positive relationship with price.
- Waterfront houses are more costly than non-waterfront houses.
- Some houses with small area still have high prices due to location or luxury features.
- Certain postal codes have significantly higher average prices.
- Most houses conatin the common bedroom count identified in the analysis.